meshery/play

- site/src/SignupForm/index.js
Added integromat scenario connection for form submissions.
> Added integromat connection for form submission

- site/src/App.js
- site/src/App.style.js
- site/src/components/SignupForm/index.js
- site/src/components/SignupForm/signupform.style.js
Updated form to use `select` instead of `radio` buttons.
> Use select instead of radio buttons in form

- site/src/components/SignupForm/index.js
As the scenario was moved to make from integromat, the hook link might stop working soon.
Better to update the hooks link now, to avoid issues in the future.
> Updated the integromat hook

- site/src/components/SignupForm/index.js
- site/src/components/SignupForm/signupform.style.js
Added the validation for at least 1 account and role in the play form.
> Added validation for accounts and role field

- site/src/components/SignupForm/index.js
Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>
This PR corrects a minor grammar error on the Thank you page.
This PR fixes #19
> Corrected minor grammar error on Thank you page

- site/src/App.style.js
- site/src/components/SignupForm/signupform.style.js
Signed-off-by: AkashGogoi <gogoiakash09@gmail.com>
This PR fixes #28
> Made Signup form responsive for smaller devices

- CONTRIBUTING.md
> Added project setup guidelines with commands

- site/src/components/SignupForm/index.js
- site/src/components/SignupForm/signupform.style.js
Signed-off-by: Rahilsiddique <siddiquerahil19@gmail.com>
https://github.com/meshery/play/issues/39
> sign up page updated

- site/src/App.js
Signed-off-by: PanyalaSainathReddy <reddy.17@iitj.ac.in>
This PR fixes #37 
**Description:**
- This PR corrects the spelling from ciricullum to curriculum 
> Corrects spelling of curriculum

- README.md
Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>
Updated Heading
> Updated Heading

- site/src/App.js
- site/src/components/Footer/index.js
This PR fixes #41
- Fixes links for Slack in the website.
> fix: fixes footer and other links for Slack

- site/src/App.js
- site/src/App.style.js
- site/src/components/Footer/index.js
This PR addresses a comment from @leecalcote (dev meeting Jan/04) about changes on the 'intent' on the playground
It also fixes a couple of small typos in the footer 
> Change 'coming soon' for 'try now'

- site/src/App.js
- site/src/App.style.js
- site/src/components/Discuss-Callout/index.js
- site/src/components/SignupForm/signupform.style.js
Signed-off-by: leecalcote <leecalcote@gmail.com>
This PR adds a login button and restyles each nav button.
> Adding login button

- CONTRIBUTING.md
Signed-off-by: Shivam-AfA <88040318+Shivam-AfA@users.noreply.github.com>
This PR fixes #51 
I have updated the contributing.md file with documentation on the working of light and dark theme.
> Added documentation for Dark theme functionality

- site/src/components/SignupForm/index.js
- site/src/components/SignupForm/signupform.style.js
This PR fixes #https://github.com/meshery/play/issues/48
> Add policies section

- site/src/App.style.js
- site/src/index.style.js
Signed-off-by: Karan Singh Thakur <karanthakur.work@gmail.com>
This PR is a follow-up for  #32 
1. Changed the text color of this button's hyperlink to #1E2117 in dark mode.
2. Increased contrast of the text in darkmode.
> feat: updated darkmode style

- site/package-lock.json
- site/package.json
- site/src/App.js
- site/src/App.style.js
**Description:**
Added the promo video with the current screenshot as the thumbnail using the `react-player` package.
Also, retained the styles to the banner :)
This PR fixes #61 
> Added promo video with banner img as thumbnail

- site/src/components/SignupForm/index.js
> Update web hook

- site/src/components/SignupForm/signupform.style.js
This is the needed change as asked in the issue https://github.com/meshery/play/issues/71
> Update hovering effect on submit button

- site/src/App.style.js
- site/src/components/Discuss-Callout/discuss.style.js
- site/src/components/SignupForm/signupform.style.js
This is a follow up to the issue raised regarding lack of transition effects on buttons.
This PR fixes #73
> Added some transition effects to buttons on the home page

- site/src/components/SignupForm/signupform.style.js
This PR fixes #77
Before:
After:
> fixed the font family for input fields and submit button

- site/src/components/SignupForm/index.js
> Updated RegEx

- site/src/components/Discuss-Callout/discuss.style.js
- site/src/components/Discuss-Callout/index.js
This PR fixes #69 
https://user-images.githubusercontent.com/116095538/221918433-5d2b1c93-67be-4aa5-b5e2-19284f97d2d5.mp4
https://user-images.githubusercontent.com/116095538/221918504-4dec541b-872a-4c0f-b9f3-aef646c0739c.mp4
> Fix: discuss.layer.io link made specific to the card

- site/src/components/SignupForm/index.js
> Mandated fields in Signup Form

- site/src/components/Navigation/Navigation.styles.js
- site/src/components/Navigation/index.js
> hamburger color changed

- site/src/components/SignupForm/index.js
> [chore] Update webhook URL

- CONTRIBUTING.md
- site/package-lock.json
- site/package.json
- site/public/index.html
- site/public/manifest.json
- site/src/components/Footer/index.js
This PR takes care of a few small, but important items.
> [Chores] footer update, login, metadata

- site/src/App.js
The text updated from "150+" to "200+" as described.
This PR fixes #95
> issue #95 fixed

- site/src/components/Discuss-Callout/index.js
I have changed the logo as described in the issue.
This PR fixes #90
> Changed logo from layer5 to meshery

- site/public/index.html
This PR updates the content attribute of meta tags for opengraph images to reference to correct address :
https://raw.githubusercontent.com/meshery/play/master/site/src/assets/images/meshery-cncf-twitter.png
> Updated og-image

- site/src/components/Footer/index.js
> fix: update year in footer from 2022 to 2023

- site/src/assets/data/faq/index.js
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>
> [Docs] More FAQs

- .github/labeler.yml
- .github/workflows/labeler.yml
> Added PR labeler

- site/src/components/SignupForm/index.js
> [chore] Update webhook URL for form

- site/public/index.html
This PR adds [meshery-cncf-twitter.png](https://raw.githubusercontent.com/meshery/play/master/site/src/assets/images/meshery-cncf-twitter.png) in `https://play.meshery.io` 's twitter preview
> add twitter preview image

- site/src/components/SignupForm/index.js
> [Chore] Update scenarios webhooks

- site/src/components/Faq/index.js
This PR fixes #113 
Added padding in UI for Meshery Playground
- [Yes ] Yes, I signed my commits.
> fix: basic enhancement|| Added PaddingBottom to  UI to enhance it's UX

- site/src/components/SignupForm/index.js
> [Chore] Update signup form webhook

- site/src/components/SignupForm/index.js
> [chore] Update webhook URL for signup form

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
> fix: issue template updates for Figma link

- site/src/components/SignupForm/index.js
> Revert "[chore] Update webhook URL for signup form"

- site/src/components/SignupForm/index.js
> Revert "fix: build workflow"

- site/src/components/SignupForm/index.js
Temporary fix for fixing the workflow failure. This will opt out of lint checking for the next line
The proper solution is to re-initialize the onsubmit function within the signupForm and call the method asynchronously. Will update the code after confirming that there are no alter effects for form submission.
> Just fix for workflow failure

- site/src/components/SignupForm/index.js
> [Chore] Update webhook

- site/src/components/SignupForm/index.js
> Revert "[Chore] Update webhook"

- site/src/components/SignupForm/index.js
> Revert "Revert "[Chore] Update webhook""

- site/src/components/SignupForm/index.js
> [Chore] Update Webhook September

- site/src/assets/data/faq/index.js
This PR fixes https://github.com/meshery/meshery.io/issues/1424
> fix: fixed typos

- site/package-lock.json
- site/src/App.js
- site/src/components/SignupForm/index.js
- site/src/components/SignupForm/signupform.style.js
This PR fixes #https://github.com/meshery/play/issues/153
> feature: added rounded corners to contact form

- site/src/components/SignupForm/index.js
Updated the role field in the sign up form to match the selections of layer5.io/meshmap
> Updated sign up form

- .github/label-commenter-config.yml
- .github/workflows/label-commenter.yml
> [Fix CI] Add Label Commenter

- site/src/components/SignupForm/index.js
> Update SignUp Form Webhook

- site/src/components/SignupForm/index.js
> [chore] Update webhook signup forms

- site/package-lock.json
- site/src/components/Faq/index.js
- site/src/components/SignupForm/index.js
> Bug #155 TextAlign Center 

- README.md
- site/src/App.js
- site/src/components/shared/discuss.style.js
- site/src/components/shared/index.js
Signed-off-by: codeKraken <160219759+codeKraken19@users.noreply.github.com>
> [UI] Add Shared Components 

- site/src/components/Navigation/index.js
Signed-off-by: codeKraken <160219759+codeKraken19@users.noreply.github.com>
> Fix Error Logging

- site/package-lock.json
- site/package.json
- site/src/assets/data/faq/index.js
- site/src/components/Faq/faqSection.style.js
- site/src/components/Faq/index.js
> Markdown support in FAQs

- site/public/index.html
This PR is a contribution for a good first issue given by the mentors in the IRC chats.
I have corrected the spelling of "Playground" in the title of [play.meshery.io](http://play.meshery.io/) as advised by the mentors.
> [BUG] corrected the name of Meshery Playground

- site/src/components/SignupForm/index.js
Reverts meshery/play#180  ( switches to signup-form-alt )
> Revert "[chore] Update webhook signup forms"

- site/src/components/Faq/faqSection.style.js
> fixes: italic effect from a text on Playground page

- site/src/components/SignupForm/index.js
> Revert "Revert "[chore] Update webhook signup forms""

- site/src/App.js
- site/src/App.style.js
- site/src/components/Navigation/Navigation.styles.js
- site/src/components/Navigation/index.js
- site/src/reusecore/Button/btn.style.js
> enhance: relocate playground-btn 

- site/src/App.js
- site/src/App.style.js
This PR adds animation to open playground button
[Screencast from 29-10-24 10:10:59 PM IST.webm](https://github.com/user-attachments/assets/ac63661d-0aa0-404d-9b9b-26303ed92b77)
> Btn animation

- README.md
> Update YouTube channel

- site/src/Resources.js
Before 
After
https://github.com/meshery/meshery.io/issues/2298
> Academy Card removed temporary

- site/src/components/VendorSelection/index.js
Signed-off-by: Marco Radicoolio <l218099172+launchmelunchme@users.noreply.github.com>
> DigitalOcean

- site/src/App.js
- site/src/components/Faq/faqSection.style.js
- site/src/components/Faq/index.js
- site/src/components/VendorSelection/index.js
- site/src/components/VendorSelection/vendorSelection.style.js
- site/src/index.style.js
Signed-off-by: Marco Radicoolio <l218099172+launchmelunchme@users.noreply.github.com>
> Playground selection enehnacements
